version: "3"

services:
  php1:
    image: php:7.4-apache
    container_name: php-container

  php2:
    build: ./php/
    container_name: php2-container

  nginx:
    image: nginx
    container_name: web-container
    ports:
      - 9088:80

  db:
    image: mysql:5.8
    container_name: db-container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: Vmware1!
      TZ: "Asia/Tokyo"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

 phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma-container
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db-container
      - PMA_USER=test
      - PMA_PASSWORD=Vmware1!
    links:
      - db
    ports:
      - '8090:80'
